Add basic support for Smartthings Oven.
athombv/com.smartthings pull request #3
Opened 2023-09-14 20:34 UTC by Allram

Add basic support for Smartthings Oven.

2024-01-31 13:23 UTC, MerelHudepohl approved these changes
I noticed that the driver icon was missing for the oven, so I've put in a request for a new icon here: [
](https://github.com/athombv/homey-vectors-public)
For future reference if you want a custom icon made for a Homey app.

2024-02-05 08:17 UTC, ttherbrink commented
Blocked by:
https://github.com/athombv/homey-vectors-public/issues/239

2024-02-05 08:42 UTC, ttherbrink requested changes
Code looks good.
Only missing the driver images.
See: https://apps.developer.homey.app/app-store/guidelines#id-1.4.-images

2024-02-21 10:34 UTC, ttherbrink approved these changes

2024-02-21 10:34 UTC, merged